import Sidebar from '@/components/sidebar'
import '../globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex w-full'>
        <Sidebar/>
        <div className='bg-green-500 min-h-screen'>
          {children}
        </div>
      </body>
    </html>
  )
}
